# Generated by Django 3.2.4 on 2021-07-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('calculations', models.BooleanField()),
                ('clinical_pharmacy', models.BooleanField()),
                ('pharmacy_law', models.BooleanField()),
                ('compounding_exam', models.BooleanField()),
                ('general_pharmacology', models.BooleanField()),
                ('imagelink', models.CharField(max_length=250)),
                ('credentials', models.JSONField()),
            ],
        ),
    ]
