# Generated by Django 3.2.4 on 2021-07-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleapi', '0004_alter_teachers_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='credentials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
