# Generated by Django 3.2.4 on 2021-07-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleapi', '0005_alter_teachers_credentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name_plural': 'teachers'},
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
